services:
  postgresql:
    container_name: postgres
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spring
